# ----------------------- #
#      Main Configs       #
# ----------------------- #

title: Daniel Easterman - Writer / Software Developer
author: Daniel Easterman
description: Journalist-turned-Developer. Coding in Python and Javascript. Interested in all things tech.
copyright: ""

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
# Causing css and js to fail:
# permalink: pretty
# Don't need this as simpler without _pages folder
# include: ["_pages"]
