# ----------------------- #
#      Main Configs       #
# ----------------------- #

title: Daniel Easterman - Founder / Software Developer
author: Daniel Easterman
description: Tools and reports every week on tech stocks and crypto.
copyright: ""

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
# Causing css and js to fail:
# permalink: pretty
# Don't need this as simpler without _pages folder
# include: ["_pages"]
