# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://daneasterman.github.io/
title: Daniel Easterman
email: daniel.easterman@gmail.com
description: "I am a web developer and former journalist with a deep passion for technology, a keen eye for design and a strong desire to always be learning."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/daneasterman
  - title: github
    url: https://github.com/daneasterman
  - title: linkedin
    url: https://uk.linkedin.com/in/danieleasterman
